create database project;
use project;
select * from categories;
select * from customers;
select * from orderdetails;
select * from orders;
select * from products;
select * from store_employees;
select * from suppliers;

describe customers;
DESCRIBE categories;
DESCRIBE orderdetails;
DESCRIBE orders;
DESCRIBE products;
DESCRIBE store_employees;
DESCRIBE suppliers;

ALTER TABLE customers
MODIFY CustomerID INT NOT NULL;

ALTER TABLE customers
ADD PRIMARY KEY (CustomerID);

ALTER TABLE orders
ADD CONSTRAINT fk_orders_customers
FOREIGN KEY (CustomerID)
REFERENCES customers(CustomerID);




-- Check parent table
DESCRIBE store_employees;

-- Make sure EmployeeID is NOT NULL
ALTER TABLE store_employees
MODIFY EmployeeID INT NOT NULL;

-- Make EmployeeID the PRIMARY KEY
ALTER TABLE store_employees
ADD PRIMARY KEY (EmployeeID);

-- Now add the FK in orders table
ALTER TABLE orders
ADD CONSTRAINT fk_orders_employees
FOREIGN KEY (EmployeeID)
REFERENCES store_employees(EmployeeID);


ALTER TABLE orderdetails
MODIFY OrderDetailID INT NOT NULL;

ALTER TABLE orderdetails
ADD PRIMARY KEY (OrderDetailID);

-- Check parent table
DESCRIBE orders;

-- Make sure OrderID is NOT NULL
ALTER TABLE orders
MODIFY OrderID INT NOT NULL;

-- Make OrderID the PRIMARY KEY
ALTER TABLE orders
ADD PRIMARY KEY (OrderID);

-- Add FK in orderdetails table
ALTER TABLE orderdetails
ADD CONSTRAINT fk_orderdetails_orders
FOREIGN KEY (OrderID)
REFERENCES orders(OrderID);


-- Check parent table
DESCRIBE products;

-- Make sure ProductID is NOT NULL
ALTER TABLE products
MODIFY ProductID INT NOT NULL;

-- Make ProductID the PRIMARY KEY
ALTER TABLE products
ADD PRIMARY KEY (ProductID);

-- Add FK in orderdetails table
ALTER TABLE orderdetails
ADD CONSTRAINT fk_orderdetails_products
FOREIGN KEY (ProductID)
REFERENCES products(ProductID);


-- Check parent table
DESCRIBE suppliers;

-- Make sure SupplierID is NOT NULL
ALTER TABLE suppliers
MODIFY SupplierID INT NOT NULL;

-- Make SupplierID the PRIMARY KEY
ALTER TABLE suppliers
ADD PRIMARY KEY (SupplierID);

-- Add FK in products table
ALTER TABLE products
ADD CONSTRAINT fk_products_suppliers
FOREIGN KEY (SupplierID)
REFERENCES suppliers(SupplierID);


-- Check parent table
DESCRIBE categories;

-- Make sure CategoryID is NOT NULL
ALTER TABLE categories
MODIFY CategoryID INT NOT NULL;

-- Make CategoryID the PRIMARY KEY
ALTER TABLE categories
ADD PRIMARY KEY (CategoryID);

-- Add FK in products table
ALTER TABLE products
ADD CONSTRAINT fk_products_categories
FOREIGN KEY (CategoryID)
REFERENCES categories(CategoryID);


-- 1. Customer Insights
--  How many unique customers have placed orders? 
SELECT COUNT(DISTINCT CustomerID) AS UniqueCustomers
FROM Orders;

--  Which customers have placed the highest number of orders? 
SELECT 
    CustomerID,
    COUNT(*) AS TotalOrders
FROM Orders
GROUP BY CustomerID
ORDER BY TotalOrders DESC limit 1;

--  What is the total and average purchase value per customer?

SELECT 
    c.customerid,
    c.name,
    SUM(od.quantity * p.price) AS total_value,
    AVG(od.quantity * p.price) AS avg_value
FROM customers c
JOIN orders o ON c.customerid = o.customerid
JOIN orderdetails od ON o.orderid = od.orderid
JOIN products p ON od.productid = p.productid
GROUP BY c.customerid, c.name;

-- Who are the top 5 customers by total purchase amount?
select  c.customerid,c.name,
 SUM(od.quantity * p.price) AS total_purchase_amount from customers c join orders o 
on c.customerid = o.customerid
join orderdetails od on o.orderid=od.orderid
join products p on od.productid = p.productid
group by c.customerid,c.name 
order by total_purchase_amount desc
limit 5;

-- 2. Product Performance
--  How many products exist in each category?
SELECT c.categoryid,c.categoryname,COUNT(p.productid) AS total_products
FROM categories c
LEFT JOIN products p 
    ON c.categoryid = p.categoryid
GROUP BY c.categoryid, c.categoryname;

-- What is the average price of products by category? 

select c.categoryid,c.categoryname, avg(p.price) from categories c 
join products p on c.categoryid=p.categoryid
group by  c.categoryid,c.categoryname;

--  Which products have the highest total sales volume (by quantity)?

SELECT 
    p.productid,
    p.name AS product_name,
    SUM(od.quantity) AS total_quantity_sold
FROM products p
JOIN orderdetails od 
    ON p.productid = od.productid
GROUP BY p.productid, p.name
ORDER BY total_quantity_sold DESC;

-- What is the total revenue generated by each product?
SELECT 
    p.productid,
    p.name AS product_name,
    SUM(od.quantity * p.price) AS total_revenue
FROM products p
JOIN orderdetails od 
    ON p.productid = od.productid
GROUP BY p.productid, p.name
ORDER BY total_revenue DESC;

--  How do product sales vary by category and supplier? 

SELECT 
    c.categoryname,
    s.suppliername,
    SUM(od.quantity) AS total_sold
FROM products p
JOIN categories c ON p.categoryid = c.categoryid
JOIN suppliers s ON p.supplierid = s.supplierid
JOIN orderdetails od ON p.productid = od.productid
GROUP BY c.categoryname, s.suppliername;


-- 3. Sales and Order Trends
--  How many orders have been placed in total? 
select count(*) as totalorders from orders;

-- What is the average value per order?

SELECT 
    AVG(t.total) AS AverageOrderValue
FROM
    (SELECT 
        orderid, SUM(totalprice) AS total
    FROM
        OrderDetails
    GROUP BY orderid) t;

-- On which dates were the most orders placed? 

select orderdate,count(*)as mostorders from orders 
group by orderdate
order by mostorders desc;

-- What are the monthly trends in order volume and revenue?

SELECT 
    DATE_FORMAT(STR_TO_DATE(orderdate, '%m/%d/%Y'), '%Y-%m') AS Month,
    COUNT(DISTINCT o.orderid) AS TotalOrders,
    SUM(od.totalprice) AS TotalRevenue
FROM orders o
JOIN orderdetails od ON o.orderid = od.orderid
GROUP BY Month
ORDER BY Month;


-- How do order patterns vary across weekdays and weekends?

SELECT
    CASE 
        WHEN DAYOFWEEK(STR_TO_DATE(orderdate, '%m/%d/%Y')) IN (1,7) THEN 'Weekend'
        ELSE 'Weekday'
    END AS DayType,
    COUNT(DISTINCT o.orderid) AS TotalOrders,
    SUM(od.totalprice) AS TotalRevenue
FROM orders o
JOIN orderdetails od ON o.orderid = od.orderid
GROUP BY DayType;
 
-- 4. Supplier Contribution

-- How many suppliers are there in the database? 
select count(*) from suppliers ;

-- ● Which supplier provides the most products?

SELECT s.suppliername, COUNT(p.productid) AS TotalProducts
FROM products p
JOIN suppliers s ON p.supplierid = s.supplierid
GROUP BY s.supplierid, s.suppliername
ORDER BY TotalProducts DESC
LIMIT 1;


-- What is the average price of products from each supplier?
select s.suppliername ,avg(p.price) as avg_price from suppliers s 
join products p on s.supplierid=p.supplierid
group by s.suppliername;

--  Which suppliers contribute the most to total product sales (by revenue)?
SELECT 
    s.suppliername,
    SUM(od.totalprice) AS TotalRevenue
FROM suppliers s
JOIN products p ON s.supplierid = p.supplierid
JOIN orderdetails od ON p.productid = od.productid
GROUP BY s.suppliername
ORDER BY TotalRevenue DESC;

--  5. Employee Performance 
--  How many employees have processed orders? 
select count(distinct(employeeid)) as employee_processed_orders from orders;


--  Which employees have handled the most orders?
select e.employeeid,e.name,COUNT(o.orderid) AS TotalOrdersHandled
 from store_employees e join orders o 
on e.employeeid = o.employeeid 
group by e.employeeid,e.name
order by e.employeeid desc;

--  What is the total sales value processed by each employee?
SELECT 
    e.employeeid,
    e.name AS employee_name,
    SUM(od.totalprice) AS TotalSalesValue
FROM store_employees e
JOIN orders o ON e.employeeid = o.employeeid
JOIN orderdetails od ON o.orderid = od.orderid
GROUP BY e.employeeid, e.name
ORDER BY TotalSalesValue DESC;


--  What is the average order value handled per employee?
select e.employeeid,e.name ,avg(od.totalprice)as avgordervalue from store_employees e join orders o 
on e.employeeid=o.employeeid
join orderdetails od on o.orderid=od.orderid 
group by e.employeeid,e.name 
order by avgordervalue desc;


-- 6. Order Details Deep Dive 
-- ● What is the relationship between quantity ordered and total price? 
SELECT 
    e.employeeid,
    e.name,
    AVG(order_totals.total) AS avg_order_value
FROM store_employees e
JOIN orders o ON e.employeeid = o.emp_id
JOIN (
        SELECT orderid, SUM(totalprice) AS total
        FROM orderdetails
        GROUP BY orderid
     ) AS order_totals
     ON o.orderid = order_totals.orderid
GROUP BY e.employeeid, e.name
ORDER BY avg_order_value DESC;


--  What is the average quantity ordered per product? 
select p.productid,p.name ,avg(od.quantity) as avgquantity from orderdetails od 
join products p on od.productid= p.productid 
group by p.productid,p.name
order by avgquantity desc; 

--  How does the unit price vary across products and orders?
SELECT 
    p.productid,
    p.name AS product_name,
    MIN(od.priceeach) AS min_unit_price,
    MAX(od.priceeach) AS max_unit_price,
    AVG(od.priceeach) AS avg_unit_price
FROM products p
JOIN orderdetails od 
    ON p.productid = od.productid
GROUP BY p.productid, p.name
ORDER BY p.productid;


